backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Page Key", name: "pageKey", widget: "hidden", default: "page_blogpost"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/pages/home/index.md"
        fields:
          - {label: "Page Key", name: "pageKey", widget: "hidden", default: "page_home"}
          - {label: "SEO Title", name: "seo_title", widget: "string"}
          - {label: "SEO Description", name: "seo_desc", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Text", name: "text", widget: "text"}
