backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Page Key", name: "pageKey", widget: "hidden", default: "page_blogpost"}
      - {label: "SEO Title", name: "seo_title", widget: "string"}
      - {label: "SEO Description", name: "seo_desc", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/pages/home/index.md"
        fields:
        - {label: "Page Key", name: "pageKey", widget: "hidden", default: "page_home"}
        - label: "SEO"
          name: "seo_comp"
          widget: "object"
          fields:
            - {label: "SEO Title", name: "seo_title", widget: "string"}
            - {label: "SEO Description", name: "seo_desc", widget: "string"}
        - label: "Video"
          name: "video_comp"
          widget: "object"
          fields:
            - label: "Video"
              name: "video"
              widget: "file"
              media_library:
                config:
                  multiple: false
            - {label: "Video Title", name: "video_text", widget: "string"}
        - label: "1. Text Compnente"
          name: "text_comp"
          widget: "object"
          fields:
            - {label: "Titel", name: "title", widget: "string"}
            - {label: "Beschreibung", name: "description", widget: "text"}
        - label: "Countdown"
          name: "countdown_comp"
          widget: "object"
          fields:
            - {label: "Jahreszeit", name: "season", widget: "string"}
            - label: "Countdown Datum"
              name: "countdown"
              widget: "date"
              default: ""
              format: "MMM Do YY"
        - label: "Fakten Slider"
          name: "facts_compt"
          widget: "object"
          fields:
            - label: "Fakten Slide"
              name: "facts"
              widget: "list"
              fields:
                - {label: Titel, name: title, widget: string}
                - {label: Text Links, name: text_left, widget: text}
                - {label: Text Rechts, name: text_right, widget: text}
        - label: "Referenzen"
          name: "referenzen"
          widget: "object"
          fields:
            - {label: "Titel", name: "title", widget: "string"}
            - {label: "Beschreibung", name: "text", widget: "text"}
            - {label: "Featured Image", name: "featuredImage", widget: "image"}